# Google App Engine configuration for GROZ APPS Website
runtime: custom
env: flex

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

# Resource configuration
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Network configuration
network:
  name: default

# Environment variables
env_variables:
  NODE_ENV: production

# Health check configuration
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300