version: '3.8'

services:
  groz-apps-website:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./models:/usr/share/nginx/html/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3